# Generated by Django 6.0.5 on 2026-05-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Nomor Urut')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Paslon')),
                ('vision', models.TextField(verbose_name='Visi')),
                ('mission', models.TextField(verbose_name='Misi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election', verbose_name='Pemilihan')),
            ],
            options={
                'verbose_name': 'Kandidat',
                'verbose_name_plural': 'Kandidat',
                'ordering': ['number'],
                'unique_together': {('election', 'number')},
            },
        ),
    ]
