# Generated by Django 5.1.1 on 2026-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PEMILIH', 'Pemilih'), ('CANDIDATE', 'Kandidat')], default='PEMILIH', max_length=10),
        ),
    ]
