# Generated by Django 6.0.5 on 2026-05-06 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Pemilihan')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('start_date', models.DateTimeField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateTimeField(verbose_name='Tanggal Selesai')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Berlangsung'), ('CLOSED', 'Selesai')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pemilihan',
                'verbose_name_plural': 'Pemilihan',
                'ordering': ['-created_at'],
            },
        ),
    ]
