# Generated by Django 6.0.5 on 2026-05-06 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Gagal'), ('ACCOUNT_LOCKED', 'Akun Terkunci'), ('VOTE_CAST', 'Suara Diberikan'), ('ELECTION_CREATED', 'Pemilihan Dibuat/Diedit'), ('ELECTION_OPENED', 'Pemilihan Dibuka'), ('ELECTION_CLOSED', 'Pemilihan Ditutup'), ('CANDIDATE_ADDED', 'Kandidat Ditambahkan'), ('CANDIDATE_UPDATED', 'Kandidat Diperbarui'), ('CANDIDATE_DELETED', 'Kandidat Dihapus'), ('USER_CREATED', 'Pengguna Dibuat/Dihapus')], max_length=30)),
                ('actor_email', models.EmailField(default='', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('log_hash', models.CharField(editable=False, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Audit',
                'verbose_name_plural': 'Log Audit',
                'ordering': ['-timestamp'],
            },
        ),
    ]
